import Head from "next/head";
import Topic from "~/components/topic";

export default function Home() {
  return (
    <>
      <Head>
        <title>Notebook</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-[calc(100vh-64px)] ">
        <Topic />
      </main>
    </>
  );
}

